# Generated by Django 5.1.1 on 2024-10-09 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8efc0ec9-d65f-41cb-b6f5-8d70caa89be5'), editable=False, unique=True),
        ),
    ]
