# Generated by Django 5.1.1 on 2024-10-05 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_seller_user_uuid_alter_user_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1d58e4dd-ac34-4dc1-a435-c136f7f5370b'), editable=False, unique=True),
        ),
    ]
