# Generated by Django 5.1.1 on 2024-10-21 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('df9f628e-de47-4921-baa9-5a206df07f74'), editable=False, unique=True),
        ),
    ]
