# Generated by Django 5.1.1 on 2024-10-07 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7996b601-bf04-42f6-ab1f-4b1d0892f055'), editable=False, unique=True),
        ),
    ]
