# Generated by Django 5.1.1 on 2024-10-02 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='expired_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='enter a valid email', regex='^[a-zA-Z0-9._%+-]+@gmail\\.com$')], verbose_name='email address'),
        ),
    ]
