# Generated by Django 5.1.1 on 2024-10-22 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('00655ba2-08c4-4459-b909-90f0c2848b22'), editable=False, unique=True),
        ),
    ]
