# Generated by Django 5.1.1 on 2024-10-23 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('071ba2d8-8779-44c7-94a5-db1489488eea'), editable=False, unique=True),
        ),
    ]
