# Generated by Django 5.1.1 on 2024-10-07 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customerprofile_is_blocked_alter_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='is_blocked',
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fc7b97aa-42ac-48c0-9135-bb75d59e92e9'), editable=False, unique=True),
        ),
    ]
