# Generated by Django 5.1.1 on 2024-10-23 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ea49277d-e58e-499b-a875-d7a2cdd55bbd'), editable=False, unique=True),
        ),
    ]
