# Generated by Django 5.1.1 on 2024-10-26 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bffd29f4-c885-46fc-bbd0-19f933f8ba89'), editable=False, unique=True),
        ),
    ]
