# Generated by Django 5.1.1 on 2024-10-26 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a6199c7b-1295-4e1b-a05d-89fb97f219ee'), editable=False, unique=True),
        ),
    ]
