# Generated by Django 5.1.1 on 2024-10-27 07:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6cf585ac-3070-46fc-ac1c-2d4a6ce819c7'), editable=False, unique=True),
        ),
    ]
