# Generated by Django 5.1.1 on 2024-10-27 08:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('19c32241-bf69-41ec-8fd1-8af9e0f5ec70'), editable=False, unique=True),
        ),
    ]
