# Generated by Django 5.1.1 on 2024-10-27 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1cf550e8-dff8-4d4d-a213-ce260002f975'), editable=False, unique=True),
        ),
    ]
