# Generated by Django 5.1.1 on 2024-10-27 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b52cc536-12d1-4d21-a9c3-128920ab1ba8'), editable=False, unique=True),
        ),
    ]
