# Generated by Django 5.1.1 on 2024-10-27 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('693fe6d6-bc93-49d9-b353-fc2f7b4ebecb'), editable=False, unique=True),
        ),
    ]
