# Generated by Django 5.1.1 on 2024-10-27 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b5252ef8-c832-4f68-872d-2c56ed2490fc'), editable=False, unique=True),
        ),
    ]
