# Generated by Django 5.1.1 on 2024-10-27 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('29470590-fb60-45be-9609-c04f233daa8d'), editable=False, unique=True),
        ),
    ]
