# Generated by Django 5.1.1 on 2024-10-27 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7a8c95d5-4486-496e-b3d7-84dbeededb88'), editable=False, unique=True),
        ),
    ]
