# Generated by Django 5.1.1 on 2024-10-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_slug_discount_discountcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
